// <auto-generated />
using System;
using Hx.Workflow.EntityFrameworkCore.DbMigrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace Hx.Abp.WeekDay.Migrations.Migrations
{
    [DbContext(typeof(HxWeekDayContext))]
    partial class HxWeekDayContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hx.Abp.WeekDay.Domain.Weekday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTime>("AdjustmentDate")
                        .HasColumnType("date")
                        .HasColumnName("ADJUSTMENTDATE");

                    b.Property<int>("AdjustmentOrganization")
                        .HasPrecision(1)
                        .HasColumnType("integer")
                        .HasColumnName("ADJUSTMENTORGANIZATION");

                    b.Property<int>("AdjustmentType")
                        .HasPrecision(1)
                        .HasColumnType("integer")
                        .HasColumnName("ADJUSTMENTTYPE");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATIONTIME");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CREATORID");

                    b.Property<int>("Day")
                        .HasPrecision(2)
                        .HasColumnType("integer")
                        .HasColumnName("DAY");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("DELETERID");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETIONTIME");

                    b.Property<string>("Description")
                        .HasPrecision(200)
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ISDELETED");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LASTMODIFICATIONTIME");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LASTMODIFIERID");

                    b.Property<int>("Month")
                        .HasPrecision(2)
                        .HasColumnType("integer")
                        .HasColumnName("MONTH");

                    b.Property<int>("Year")
                        .HasPrecision(4)
                        .HasColumnType("integer")
                        .HasColumnName("YEAR");

                    b.HasKey("Id");

                    b.ToTable("HXWEEKDAYS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
